config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get "home" => "home#index"
  
  get "home/formulario" 
 
  get "editar/:id" => "home#editar"
  post "grabar" => "home#grabar"

  get "borrar/:id" => "home#borrar"

end

app/models/arriendo.rb
class Arriendo < ActiveRecord::Base
  belongs_to :movie
  belongs_to :serie
  belongs_to :user
  
  def self.ultimo
    ultimo = self.last.id + 1
    return ultimo
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :arriendos
end

app/models/serie.rb
class Serie < ActiveRecord::Base
  has_many :arriendos
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :arriendos , dependent: :destroy
  
  def self.ultimo
    ultimo = self.last.id + 1
    return ultimo
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index

    @arriendos = User.select('users.id u_id','users.nombre u_nombre','users.email u_email')
                       
  end
  
  def formulario
    @series = Serie.all
    @peliculas = Movie.all
  end
  
  def crear_arriendos(usuario,hash_movie,hash_arriendo)
    
    hash_movie.each do |mo|
      usuario.arriendos.create(id: Arriendo.ultimo, movie_id: mo, serie_id: 0)
    end
    
    hash_arriendo.each do |se|
      usuario.arriendos.create(id: Arriendo.ultimo, movie_id: 0, serie_id: se)
    end
  end
  
  def grabar
    @id_user = params[:id]
    

    if @id_user!=nil && @id_user!=""
      @user = User.find_by(id: @id_user)
      @user.nombre = params[:usuario]['nombre']
      @user.email = params[:usuario]['email']
      @user.save

      Arriendo.where(user_id: @id_user).destroy_all
    else
      get_nombre = params[:usuario]['nombre']
      get_email = params[:usuario]['email']
      
      @user = User.create(id: User.ultimo , nombre: get_nombre, email: get_email)
    
    end
  
    crear_arriendos(@user,params[:movie],params[:serie])
    redirect_to home_path
  end
  
  def borrar
    usuario = User.find(params[:id])
    
    usuario.destroy
    redirect_to home_path
  end
  
  def editar
    @series = Serie.all
    @peliculas = Movie.all

    @editar = User.select('users.id u_id','users.nombre u_nombre','users.email u_email').find_by(id: params[:id])

    @get_movies = Arriendo.select('movies.id','movies.titulo')
                  .joins(:movie)
                  .where(:user_id => params[:id])
                  
                  
    @get_series = Arriendo.select('series.id','series.titulo')
                  .joins(:serie)
                  .where(:user_id => params[:id])
                  
    @array_movies = Array.new
    @array_series = Array.new
    
    @get_movies.each do |array|
     @array_movies.push(array.id)
    end
    
    @get_series.each do |array|
     @array_series.push(array.id)
    end


  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/editar.html.erb
<script>
  $(document).ready(function(){
    
    $( "#id_movies, #id_series" ).select2({
    multiple:true
    });
    
  });
  
</script>

  
  <h3>Editar: </h3>
  
    <%= form_tag(grabar_path, method: "post", :class => 'form-horizontal', :role => 'form', :multipart => true )  do %>

      <hr />

        <input type='hidden' value="<%= @editar.try(:u_id) %>" name='id' />
    

      <div class="form-group">
          <label for="" class="col-xs-2 col-sm-2 col-md-2 control-label" style="color: black;">Nombre</label>
          <div class="col-xs-offset-1 col-xs-4 col-sm-4 col-md-6">
              <input type="text" required name="usuario[nombre]" pattern="[a-zA-Z\ ]{3,25}" placeholder="Ej : Juan Pablo" class="form-control" value="<%= @editar.try(:u_nombre) %>"/>
          </div>
      </div>
      
      <hr />

      <div class="form-group">
          <label for="" class="col-xs-2 col-sm-2 col-md-2 control-label" style="color: black;">Email</label>
          <div class="col-xs-offset-1 col-xs-4 col-sm-4 col-md-4">
              <input type="text" required name="usuario[email]"  pattern="^.+@.+$"  class="form-control"  placeholder="Ej : xxxxx@xxxxxx.xxx" value="<%= @editar.try(:u_email) %>"/>
          </div>
      </div>

      <hr />

       <div class="form-group">
            <label for="" class="col-xs-2 col-sm-2 col-md-2 control-label" style="color: black;">Productos(*)</label>
            <div class="col-xs-offset-1 col-xs-10 col-sm-10 col-md-10">
         
                <!-- MULTI SELECT-->   
          
              peliculas
              <%= select_tag "movie", options_from_collection_for_select(Movie.all,"id","titulo", :selected=>@array_movies), :multiple => true, :id => "id_movies", :class => "class_html form-control" %>  
              
              series
              <%= select_tag "serie", options_from_collection_for_select(Serie.all,"id","titulo", :selected=>@array_series), :multiple => true, :id => "id_series", :class => "class_html form-control" %>   
            </div>
        </div>

      <hr />

 <div class="form-group">

          <div class="col-xs-offset-3 col-xs-3 col-sm-3 col-md-3">
              <input type="submit" id="actualizar" value="Guardar Cambios" style="width: 100%; font-size: 130%" class="btn btn-primary registrar"/>
              <a href='<%= home_path %>' class='btn btn-success '>Volver</a>
          </div>
 </div>
				   

<% end %>

  

app/views/home/index.html.erb
  <%= link_to "Agendar Arriendo ", "/editar/new", class: "btn btn-success" %>

    <% if @arriendos[0]==nil %>
      <div class="alert alert-success">
        <center><strong>No hay registros</strong> </center>
      </div>
    <% else %>
     <h3>Arriendos actuales: </h3>
    
     <table class="table table-hover table-dark">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Email</th>
                <th scope="col">Productos</th>
                <th scope="col">opciones</th>
              </tr>
            </thead>
            <tbody>
              <%  @arriendos.each do |item| %>
              <tr class="">
                <th scope="row"><%= item.u_id %></th>
                <td><%= item.u_nombre %></td>
                <td><%= item.u_email %></td>
                <td>
                  <% @movie = Arriendo.select('movies.titulo')
                  .joins(:movie)
                  .where(:user_id => item.u_id) %>
                  
                    <%  @movie.each do |pelicula| %>
                      |<%= pelicula.titulo %>|
                    <% end %> 
                  
                  <% @serie = Arriendo.select('series.titulo')
                  .joins(:serie)
                  .where(:user_id => item.u_id) %>
                  
                    <%  @serie.each do |serie| %>
                      |<%= serie.titulo %> |
                    <% end %> 
                </td>
                <td>
                	
                  <%= link_to "Borrar", "/borrar/#{item.u_id}", class: "btn btn-danger" %>
                  <%= link_to "Editar ", "/editar/#{item.u_id}", class: "btn btn-primary" %>
                </td>
              </tr>
              <% end %>
              
            </tbody>
      </table>
      
  
    <% end %>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pelis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  
  <center><h1>Películas</h1></center><hr>
  
<%= yield %>
  
</div>

</body>
</html>